
//Details
export const LOAD_EVENTS = "LOAD_EVENTS";
export const LOAD_EVENT_DETAILS= "LOAD_EVENT_DETAILS"
export const SET_EVENT_SCROLL = "SET_EVENT_SCROLL";
export const RESET_EVENT_STATE = "RESET_EVENT_STATE";


//Lookups
export const LOAD_EVENT_TYPE = "LOAD_EVENT_TYPE";
export const LOAD_REGION = "LOAD_REGION";
export const LOAD_HAZARD = "LOAD_HAZARD";
export const LOAD_IMPACT = "LOAD_IMPACT"

//Filters
export const LOAD_REGION_FILTER = "LOAD_REGION_FILTER";
export const LOAD_HAZARD_FILTER = "LOAD_HAZARD_FILTER"
export const LOAD_IMPACT_FILTER = "LOAD_IMPACT_FILTER"
export const LOAD_STARTDATE_FILTER = "LOAD_IMPACT_FILTER"
export const LOAD_ENDDATE_FILTER = "LOAD_IMPACT_FILTER"
export const CLEAR_FILTERS = "CLEAR_FILTERS";

//Trees
export const LOAD_REGION_TREE = "LOAD_REGION_TREE";
export const LOAD_HAZARD_TREE = "LOAD_HAZARD_TREE";
export const LOAD_IMPACT_TREE = "LOAD_IMPACT_TREE";

//Global
export const SET_LOADING = "SET_LOADING";

//General
export const LOAD_MORE_EVENTS = "LOAD_MORE_EVENTS";
export const RESET_EVENT_COUNTS = "RESET_EVENT_COUNTS";